[general]
bars = 64
sleep_timer = 0
framerate = 60

[input]
method = pipewire
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 1000
bar_delimiter = 59
frame_delimiter = 10
channels = stereo
reverse = 0
